# Generated by Django 4.0.3 on 2022-05-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='notice/post/%Y/%m')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=400)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
