# Generated by Django 4.0.3 on 2022-05-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='notice/post/%Y/%m'),
        ),
    ]
